"""lealtad_y_programados

Revision ID: 0bba8a2ef89f
Revises: de5e4ddd3359
Create Date: 2026-07-06 10:33:42.815508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bba8a2ef89f'
down_revision: Union[str, None] = 'de5e4ddd3359'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default para filas existentes (nunca tuvieron puntos)
    op.add_column('customers', sa.Column('loyalty_points', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('orders', sa.Column('points_redeemed', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('orders', sa.Column('points_discount', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'))
    op.add_column('orders', sa.Column('points_awarded', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('orders', sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'scheduled_for')
    op.drop_column('orders', 'points_awarded')
    op.drop_column('orders', 'points_discount')
    op.drop_column('orders', 'points_redeemed')
    op.drop_column('customers', 'loyalty_points')
    # ### end Alembic commands ###
