"""recetas_y_descuento_insumos

Revision ID: 1273f36edc24
Revises: a5e60587650b
Create Date: 2026-07-06 04:46:41.952629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1273f36edc24'
down_revision: Union[str, None] = 'a5e60587650b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu_item_supplies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('menu_item_id', sa.Integer(), nullable=False),
    sa.Column('supply_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supply_id'], ['supplies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('menu_item_id', 'supply_id', name='uq_receta_menu_supply')
    )
    # server_default para las filas existentes (pedidos previos nunca descontaron insumos)
    op.add_column('orders', sa.Column('supplies_deducted', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'supplies_deducted')
    op.drop_table('menu_item_supplies')
    # ### end Alembic commands ###
