"""agregar campos mercadopago a orders

Revision ID: 3850a31c4be3
Revises: 2f61d6d69fe0
Create Date: 2026-07-04 23:18:11.143073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3850a31c4be3'
down_revision: Union[str, None] = '2f61d6d69fe0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('mp_preference_id', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('mp_payment_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'mp_payment_id')
    op.drop_column('orders', 'mp_preference_id')
    # ### end Alembic commands ###
