"""proveedor_insumo

Revision ID: 7cfdb8a44961
Revises: 1273f36edc24
Create Date: 2026-07-06 05:22:38.018681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cfdb8a44961'
down_revision: Union[str, None] = '1273f36edc24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplies', sa.Column('supplier_name', sa.String(length=255), nullable=True))
    op.add_column('supplies', sa.Column('supplier_phone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supplies', 'supplier_phone')
    op.drop_column('supplies', 'supplier_name')
    # ### end Alembic commands ###
