"""agregar_insumos

Revision ID: a053eaef627b
Revises: 3850a31c4be3
Create Date: 2026-07-06 04:21:35.595167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a053eaef627b'
down_revision: Union[str, None] = '3850a31c4be3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('current_stock', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('min_stock', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('cost_per_unit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('supply_movements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('supply_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('ENTRADA', 'SALIDA', 'MERMA', 'AJUSTE', name='supply_movement_type'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('stock_before', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('stock_after', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('admin_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['supply_id'], ['supplies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supply_movements')
    op.drop_table('supplies')
    # ### end Alembic commands ###
